DM-33453: Update pipelines to match drp_pipe naming
lsst/ap_pipe pull request #150
Opened 2023-09-15 19:54 UTC by erinleighh

Changed `HyperSuprimeCam` to `HSC`, `DarkEnergyCamera` to `DECam`, and `LSSTCamImSim` to `LSSTCam-imSim` to match `drp_pipe` naming while providing backwards compatibility.

2023-09-19 17:13 UTC, kfindeisen requested changes
I think something's gone wrong with the move, because there are now _both_ old-style and new-style directories: https://github.com/lsst/ap_pipe/tree/ad29150c5e43bd8d75438a7a013dac95e3120851/pipelines.

Please update `pipelines/README.md`; its example uses the old-style directory name. (I've checked with GitHub search that this seems to be the only dangling reference, but GH doesn't let you search branches so you might want to double-check.)

I'm also a bit concerned about the wording of the commit message -- it sounds as if we were arbitrarily following the DRP group's lead, rather than implementing something we all agreed to ([RFC-775](https://jira.lsstcorp.org/browse/RFC-775)). Maybe nobody will ever read it, but it still feels like a misrepresentation.

2023-09-19 17:33 UTC, erinleighh commented on pipelines/DarkEnergyCamera/ApPipe.yaml
They're supposed to be symbolic links for backwards compatibility. I discussed it a bit with Ian and Eric, though there was no end date for when we'll get rid of the sym links.

2023-09-19 17:48 UTC, kfindeisen commented on pipelines/DarkEnergyCamera/ApPipe.yaml
Ok, that makes sense. However, it's a bit problematic since we _do_ need to get rid of those directories (that was the whole point!), and we don't have a way to add a deprecation warning to symlinks.

I think a hard break is the lesser evil in this case, but if not, please at least file a removal ticket and block it on one of the upcoming releases as if we were following [the deprecation policy](https://developer.lsst.io/stack/deprecating-interfaces.html).

2023-09-19 19:01 UTC, kfindeisen commented on pipelines/DarkEnergyCamera/ApPipe.yaml
Actually, one other request: could the symlinks be split off into their own commit? I think it might help git/GitHub be less confused about the net diff, as well as providing a natural division of the changes (essential vs. non-essential).

2024-01-29 18:16 UTC, kfindeisen approved these changes

2024-01-29 18:41 UTC, kfindeisen commented on pipelines/README.md
Oops, found a problem -- the link on line 9 needs to be updated as well.

2024-01-30 05:58 UTC, merged