DM-43414: Update make_apdb module for changes in APDB API
lsst/ap_pipe pull request #173
Opened 2024-03-25 03:58 UTC by andy-slac

`make_apdb` will be replaced by `apdb-cli` sub-command, for now we keep it for compatibility reasons, but update it for new APDB API. This script depends on using pex_config for Apdb configuration, that will be replaced eventually with something different, we may want to drop this script before that change.

2024-03-29 23:52 UTC, kfindeisen submitted a review, later dismissed
I recommend using a deprecation warning instead of a comment, otherwise people will keep using `make_apdb` indefinitely.

2024-03-29 23:52 UTC, kfindeisen commented on python/lsst/ap/pipe/make_apdb.py
> +    # backward compatibility, but only support SQL implementation here.
If you want to remove `make_apdb.py`, I suggest emitting a deprecation warning when it's run.

2024-03-30 00:00 UTC, kfindeisen requested changes
I recommend emitting a deprecation warning from `make_apdb.py`, otherwise people will keep using it indefinitely.

On that note, please update the docs with the recommended idioms:
* doc/lsst.ap/pipe/pipeline-tutorial.rst
* doc/lsst.ap/pipe/apdb.rst
* The comments at the top of pipelines/*/ApPipe*.yaml
* https://github.com/lsst-dm/prompt_processing/blob/main/doc/playbook.rst#databases

2024-04-01 23:05 UTC, andy-slac commented on python/lsst/ap/pipe/make_apdb.py
> +    # backward compatibility, but only support SQL implementation here.
What is the preferred style for deprecation messages? I could just `print(stderr)`, or do `warnings.warn(FutureWarning)`?

2024-04-01 23:09 UTC, timj commented on python/lsst/ap/pipe/make_apdb.py
> +    # backward compatibility, but only support SQL implementation here.
We prefer `warnings.warn` I think. We then have the option of forwarding them to logging easily.

2024-04-01 23:25 UTC, kfindeisen commented on python/lsst/ap/pipe/make_apdb.py
> +    # backward compatibility, but only support SQL implementation here.
I think you can use the standard deprecation annotation, see https://developer.lsst.io/stack/deprecating-interfaces.html#python-deprecation.

2024-04-02 17:55 UTC, andy-slac commented
@kfindeisen, I added deprecation, updated docs and pipelines. PR for prompt_processing playbook is here: https://github.com/lsst-dm/prompt_processing/pull/151

2024-04-02 19:06 UTC, kfindeisen approved these changes
I think the main user guide for `apdb-cli` should be in the same package (i.e., `dax_apdb`), but happy to leave that for later. DM-43416 will require another rewrite of this text anyway. 🙂

2024-04-02 19:27 UTC, andy-slac commented on doc/lsst.ap.pipe/apdb.rst
> +Note that this document applies to APDB implementation backed by SQL database (SQLite or PostgreSQL), Cassandra-based implementation will use different set of options.
Agree, apdb documentation needs some care, I hope I can spend some time on it when major tasks are finished.

2024-04-02 22:15 UTC, merged